import {useEffect, useMemo, useRef, useState} from 'react';

const DATA_TYPE_OPTIONS = [
    'serial',
    'bigserial',
    'smallserial',
    'integer',
    'bigint',
    'smallint',
    'numeric',
    'decimal',
    'real',
    'double precision',
    'money',
    'varchar',
    'char',
    'text',
    'boolean',
    'uuid',
    'date',
    'time',
    'timetz',
    'timestamp',
    'timestamptz',
    'interval',
    'json',
    'jsonb',
    'bytea',
    'inet',
    'cidr',
    'macaddr',
    'xml',
    'tsvector',
    'tsquery',
    'citext',
    'point',
    'line',
    'lseg',
    'box',
    'path',
    'polygon',
    'circle',
    'bit',
    'varbit',
    'enum',
    'array'
];

const COMMON_TYPES = new Set([
    'serial',
    'bigserial',
    'integer',
    'bigint',
    'smallint',
    'numeric',
    'decimal',
    'varchar',
    'text',
    'boolean',
    'uuid',
    'date',
    'timestamp',
    'timestamptz',
    'json',
    'jsonb'
]);
